version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "main"
    automerge:
      labels:
        - "dependencies"
    labels:
      - "dependencies"
    assignees:
      - "QuentinLemCode"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "main"
    automerge:
      labels:
        - "workflow"
    labels:
      - "workflow"
    assignees:
      - "QuentinLemCode"
